language: php

php:
  - 7
  - 5.6
  - hhvm

env:
  - LARAVEL_VERSION="~5.2" TESTBENCH_VERSION="~3.2"

before_script:
  - travis_retry composer install --no-interaction --prefer-source

script: phpunit

sudo: false

notifications:
  slack: asgardcms:p4i0eRhlenQrEOQDUba8NQyu
  email:
    - n.widart@gmail.com
    - josh@joshbrown.me

matrix:
  allow_failures:
    - php: hhvm
