language: php

php:
  - 7
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache

env:
  - LARAVEL_VERSION="~5.3" TESTBENCH_VERSION="~3.3"

before_script:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - chmod +x travis.sh
  - ./travis.sh

script: phpunit

sudo: false

